apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: service-pulse
  labels:
    app.kubernetes.io/name: mysql-server
    app.kubernetes.io/part-of: service-pulse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
